//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_14
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallSeat
    {
        public int ID { get; set; }
        public int HallID { get; set; }
        public int SeatID { get; set; }
        public bool IsTaken { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
