//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public int SessionID { get; set; }
        public int SeatID { get; set; }
        public int UserID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Users Users { get; set; }
    }
}
