//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserID { get; set; }
    
        public virtual OrdersProducts OrdersProducts { get; set; }
        public virtual Users Users { get; set; }
    }
}
