//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
