//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_details
    {
        public int Shop_id { get; set; }
        public Nullable<int> Detail_id { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Details Details { get; set; }
    }
}
