//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf17
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterServiceType()
        {
            this.Record = new HashSet<Record>();
        }
    
        public int MasterServiceTypeID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<int> WeekDayID { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual User User { get; set; }
        public virtual WeekDay WeekDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
    }
}
