//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public int ClientID { get; set; }
        public int MasterID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ServiceTypeID { get; set; }
        public decimal Price { get; set; }
        public int PaymentTypeID { get; set; }
        public string Comment { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
